# Generated by Django 5.2.16 on 2026-07-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('price', models.CharField(max_length=100, verbose_name='Стоимость')),
                ('duration', models.CharField(max_length=100, verbose_name='Длительность')),
            ],
            options={
                'verbose_name': 'Позиция прайса',
                'verbose_name_plural': 'Прайс-лист',
                'ordering': ('id',),
            },
        ),
    ]
