# Generated by Django 5.2.16 on 2026-07-28 12:03

from django.db import migrations

SEED_PRICES = (
    {
        'title': 'Очная консультация',
        'description': 'Личная встреча в кабинете психолога.',
        'price': '3000 ₽',
        'duration': '50 минут',
    },
    {
        'title': 'Онлайн-консультация',
        'description': 'Видеозвонок в удобном для вас мессенджере или сервисе.',
        'price': '2500 ₽',
        'duration': '50 минут',
    },
    {
        'title': 'Текстовая консультация',
        'description': 'Переписка в чате в комфортном темпе, без созвона.',
        'price': '1500 ₽',
        'duration': 'в течение суток',
    },
)


def seed_service_prices(apps, schema_editor):
    ServicePrice = apps.get_model('pages', 'ServicePrice')
    ServicePrice.objects.bulk_create(ServicePrice(**data) for data in SEED_PRICES)


def remove_service_prices(apps, schema_editor):
    ServicePrice = apps.get_model('pages', 'ServicePrice')
    ServicePrice.objects.filter(title__in=[data['title'] for data in SEED_PRICES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_service_prices, remove_service_prices),
    ]
