# Пользователи (users)
USER_EMAIL_FIELD_MAX_LENGTH = 254
USER_CHAR_FIELD_MAX_LENGTH = 150
FORBIDDEN_USERNAMES = ('me',)

# Статьи (articles)
ARTICLE_TITLE_MAX_LENGTH = 200
ARTICLE_SLUG_MAX_LENGTH = 200
ARTICLE_PENDING_FORM_SESSION_KEY = 'pending_article_form'
ARTICLE_LIST_PAGE_SIZE = 10

# Оценки (ratings)
RATING_MIN_VALUE = 1
RATING_MAX_VALUE = 5
RATING_CHOICES = [(i, str(i)) for i in range(RATING_MIN_VALUE, RATING_MAX_VALUE + 1)]

# Комментарии (comments)
VISUAL_NAME_LIMIT = 30
COMMENT_FORM_ROWS = 3

# Заявки на консультацию (consultations)
CONSULTATION_NAME_MAX_LENGTH = 150
CONSULTATION_CONTACT_VALUE_MAX_LENGTH = 254
CONSULTATION_CHOICE_FIELD_MAX_LENGTH = 20

CONSULTATION_FORM_ROWS = 4
STAFF_PANEL_PAGE_SIZE = 50
CONSULTATION_SESSION_CLAIM_KEY = 'anonymous_consultation_ids'
CONSULTATION_SESSION_CLAIM_TTL_SECONDS = 3600

CONSULTATION_STATUS_NEW = 'new'
CONSULTATION_STATUS_IN_PROGRESS = 'in_progress'
CONSULTATION_STATUS_CLOSED = 'closed'
CONSULTATION_STATUS_CHOICES = (
    (CONSULTATION_STATUS_NEW, 'Новая'),
    (CONSULTATION_STATUS_IN_PROGRESS, 'В работе'),
    (CONSULTATION_STATUS_CLOSED, 'Закрыта'),
)

CONTACT_METHOD_PHONE = 'phone'
CONTACT_METHOD_EMAIL = 'email'
CONTACT_METHOD_TELEGRAM = 'telegram'
CONTACT_METHOD_WHATSAPP = 'whatsapp'
CONTACT_METHOD_CHOICES = (
    (CONTACT_METHOD_PHONE, 'Телефон'),
    (CONTACT_METHOD_EMAIL, 'Email'),
    (CONTACT_METHOD_TELEGRAM, 'Telegram'),
    (CONTACT_METHOD_WHATSAPP, 'WhatsApp'),
)

# Уведомления (notifications)
TELEGRAM_REQUEST_TIMEOUT_SECONDS = 5
EMAIL_TIMEOUT_SECONDS = 5

# Настройки проекта (settings)
JWT_ACCESS_TOKEN_LIFETIME_MINUTES = 30
JWT_REFRESH_TOKEN_LIFETIME_DAYS = 7
API_PAGE_SIZE = 10
DEFAULT_EMAIL_PORT = 587
DEFAULT_DB_PORT = 5432

# Сообщения об ошибках (используются и в DRF-исключениях, и в обычных Django-формах)
DUPLICATE_RATING_MESSAGE = 'Вы уже оценили эту статью.'

# Антиспам (anti-spam)
CONSULTATION_CREATE_THROTTLE_SCOPE = 'consultation_create'
CONSULTATION_CREATE_THROTTLE_RATE = '5/hour'

CONSULTATION_CREATE_RATE_LIMIT = 5
CONSULTATION_CREATE_RATE_LIMIT_WINDOW_SECONDS = 3600
HONEYPOT_FIELD_NAME = 'website'
HONEYPOT_ERROR_MESSAGE = 'Обнаружен спам.'

FORM_SESSION_WRITE_RATE_LIMIT = 5
FORM_SESSION_WRITE_RATE_LIMIT_WINDOW_SECONDS = 3600

COMMENT_CREATE_THROTTLE_SCOPE = 'comment_create'
COMMENT_CREATE_THROTTLE_RATE = '20/hour'
COMMENT_CREATE_RATE_LIMIT = 20
COMMENT_CREATE_RATE_LIMIT_WINDOW_SECONDS = 3600

# Статичные страницы (pages)
HOME_RECENT_ARTICLES_COUNT = 3

# Прайс-лист (service prices)
SERVICE_PRICE_TITLE_MAX_LENGTH = 150
SERVICE_PRICE_VALUE_MAX_LENGTH = 100
SERVICE_PRICE_DESCRIPTION_MAX_LENGTH = 300
