# Generated by Django 5.2.16 on 2026-10-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premoderation_enabled', models.BooleanField(default=False, help_text='Новые комментарии обычных пользователей появятся на сайте только после одобрения в разделе «Комментарии». Комментарии сотрудников публикуются сразу. Уже ожидающие одобрения комментарии при выключении не публикуются сами.', verbose_name='Премодерация комментариев')),
            ],
            options={
                'verbose_name': 'Настройки комментариев',
                'verbose_name_plural': 'Настройки комментариев',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Одобрен'),
        ),
    ]
